### ISSUE TITLE
Cloud interface very very slow

### ISSUE THREAD

**Issue by exablaze-dev** [kerberos-io/cloud#2]
It would be good if the files produced are stored in amazon in the local region or I'm assuming that;s the issue.

As we are trying to view our files from Australia and the web interface is mostly blank, with the camera view being a black rectangle.

**Comment by cedricve** [comment]
hey @exablaze-dev, do you still have the issue?

**Comment by exablaze-dev** [comment]
Hi, I think it was related to the box we were using running out of disk space.  As soon as I resloved that issue.  The interface seemed to improve
